//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgeFit.MAUI.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ForgeFit.MAUI.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConnectionFailedMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedMessage", resourceCulture);
            }
        }
        
        internal static string ConnectionTimedOutMessage {
            get {
                return ResourceManager.GetString("ConnectionTimedOutMessage", resourceCulture);
            }
        }
        
        internal static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        internal static string EmptyFieldsMessage {
            get {
                return ResourceManager.GetString("EmptyFieldsMessage", resourceCulture);
            }
        }
        
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        internal static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        internal static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        internal static string ServerErrorPrefix {
            get {
                return ResourceManager.GetString("ServerErrorPrefix", resourceCulture);
            }
        }
        
        internal static string ServerUnavailableMessage {
            get {
                return ResourceManager.GetString("ServerUnavailableMessage", resourceCulture);
            }
        }
        
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        internal static string DiaryPageTitle {
            get {
                return ResourceManager.GetString("DiaryPageTitle", resourceCulture);
            }
        }
        
        internal static string WorkoutPageTitle {
            get {
                return ResourceManager.GetString("WorkoutPageTitle", resourceCulture);
            }
        }
        
        internal static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        internal static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        internal static string Diary_Title {
            get {
                return ResourceManager.GetString("Diary_Title", resourceCulture);
            }
        }
        
        internal static string Diary_Summary {
            get {
                return ResourceManager.GetString("Diary_Summary", resourceCulture);
            }
        }
        
        internal static string Diary_Meals {
            get {
                return ResourceManager.GetString("Diary_Meals", resourceCulture);
            }
        }
        
        internal static string Diary_Hydration {
            get {
                return ResourceManager.GetString("Diary_Hydration", resourceCulture);
            }
        }
        
        internal static string Diary_Weight {
            get {
                return ResourceManager.GetString("Diary_Weight", resourceCulture);
            }
        }
        
        internal static string Nutrient_Carbs {
            get {
                return ResourceManager.GetString("Nutrient_Carbs", resourceCulture);
            }
        }
        
        internal static string Nutrient_Protein {
            get {
                return ResourceManager.GetString("Nutrient_Protein", resourceCulture);
            }
        }
        
        internal static string Nutrient_Fat {
            get {
                return ResourceManager.GetString("Nutrient_Fat", resourceCulture);
            }
        }
        
        internal static string Nutrient_Calories {
            get {
                return ResourceManager.GetString("Nutrient_Calories", resourceCulture);
            }
        }
        
        internal static string Nutrient_Kcal {
            get {
                return ResourceManager.GetString("Nutrient_Kcal", resourceCulture);
            }
        }
        
        internal static string Nutrient_Water {
            get {
                return ResourceManager.GetString("Nutrient_Water", resourceCulture);
            }
        }
        
        internal static string Nutrient_Fiber {
            get {
                return ResourceManager.GetString("Nutrient_Fiber", resourceCulture);
            }
        }
        
        internal static string Nutrient_Sugar {
            get {
                return ResourceManager.GetString("Nutrient_Sugar", resourceCulture);
            }
        }
        
        internal static string Nutrient_SaturatedFat {
            get {
                return ResourceManager.GetString("Nutrient_SaturatedFat", resourceCulture);
            }
        }
        
        internal static string Nutrient_Sodium {
            get {
                return ResourceManager.GetString("Nutrient_Sodium", resourceCulture);
            }
        }
        
        internal static string Meal_Breakfast {
            get {
                return ResourceManager.GetString("Meal_Breakfast", resourceCulture);
            }
        }
        
        internal static string Meal_Lunch {
            get {
                return ResourceManager.GetString("Meal_Lunch", resourceCulture);
            }
        }
        
        internal static string Meal_Dinner {
            get {
                return ResourceManager.GetString("Meal_Dinner", resourceCulture);
            }
        }
        
        internal static string Meal_Snack {
            get {
                return ResourceManager.GetString("Meal_Snack", resourceCulture);
            }
        }
        
        internal static string Weight_Goal {
            get {
                return ResourceManager.GetString("Weight_Goal", resourceCulture);
            }
        }
        
        internal static string Weight_Left {
            get {
                return ResourceManager.GetString("Weight_Left", resourceCulture);
            }
        }
        
        internal static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        internal static string Action_AddFood {
            get {
                return ResourceManager.GetString("Action_AddFood", resourceCulture);
            }
        }
        
        internal static string Search_Header_Add {
            get {
                return ResourceManager.GetString("Search_Header_Add", resourceCulture);
            }
        }
        
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        internal static string Search_Empty {
            get {
                return ResourceManager.GetString("Search_Empty", resourceCulture);
            }
        }
        
        internal static string Search_Barcode {
            get {
                return ResourceManager.GetString("Search_Barcode", resourceCulture);
            }
        }
        
        internal static string Details_FoodProducts {
            get {
                return ResourceManager.GetString("Details_FoodProducts", resourceCulture);
            }
        }
        
        internal static string Details_Empty {
            get {
                return ResourceManager.GetString("Details_Empty", resourceCulture);
            }
        }
        
        internal static string Details_Unit {
            get {
                return ResourceManager.GetString("Details_Unit", resourceCulture);
            }
        }
        
        internal static string Hydration_Empty {
            get {
                return ResourceManager.GetString("Hydration_Empty", resourceCulture);
            }
        }
        
        internal static string Hydration_Ml {
            get {
                return ResourceManager.GetString("Hydration_Ml", resourceCulture);
            }
        }
        
        internal static string Weight_Kg {
            get {
                return ResourceManager.GetString("Weight_Kg", resourceCulture);
            }
        }
        
        internal static string Error_Oops {
            get {
                return ResourceManager.GetString("Error_Oops", resourceCulture);
            }
        }
        
        internal static string Action_Retry {
            get {
                return ResourceManager.GetString("Action_Retry", resourceCulture);
            }
        }
        
        internal static string Search_ResultsFor {
            get {
                return ResourceManager.GetString("Search_ResultsFor", resourceCulture);
            }
        }
        
        internal static string Search_Recent {
            get {
                return ResourceManager.GetString("Search_Recent", resourceCulture);
            }
        }
        
        internal static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        internal static string Hydration_Custom {
            get {
                return ResourceManager.GetString("Hydration_Custom", resourceCulture);
            }
        }
        
        internal static string Height_Cm {
            get {
                return ResourceManager.GetString("Height_Cm", resourceCulture);
            }
        }
        
        internal static string Profile_MyGoals {
            get {
                return ResourceManager.GetString("Profile_MyGoals", resourceCulture);
            }
        }
        
        internal static string Profile_MyGoals_WorkoutsPerWeek {
            get {
                return ResourceManager.GetString("Profile_MyGoals_WorkoutsPerWeek", resourceCulture);
            }
        }
        
        internal static string Profile_UpdatePlan {
            get {
                return ResourceManager.GetString("Profile_UpdatePlan", resourceCulture);
            }
        }
        
        internal static string Profile_NutritionGoal {
            get {
                return ResourceManager.GetString("Profile_NutritionGoal", resourceCulture);
            }
        }
        
        internal static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        internal static string Profile_WorkoutGoal {
            get {
                return ResourceManager.GetString("Profile_WorkoutGoal", resourceCulture);
            }
        }
        
        internal static string Workout_Frequency {
            get {
                return ResourceManager.GetString("Workout_Frequency", resourceCulture);
            }
        }
        
        internal static string Workout_Duration {
            get {
                return ResourceManager.GetString("Workout_Duration", resourceCulture);
            }
        }
        
        internal static string Workout_Type {
            get {
                return ResourceManager.GetString("Workout_Type", resourceCulture);
            }
        }
        
        internal static string Profile_Account {
            get {
                return ResourceManager.GetString("Profile_Account", resourceCulture);
            }
        }
        
        internal static string Action_ChangePassword {
            get {
                return ResourceManager.GetString("Action_ChangePassword", resourceCulture);
            }
        }
        
        internal static string Action_Logout {
            get {
                return ResourceManager.GetString("Action_Logout", resourceCulture);
            }
        }
        
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        internal static string Password_Old {
            get {
                return ResourceManager.GetString("Password_Old", resourceCulture);
            }
        }
        
        internal static string Password_New {
            get {
                return ResourceManager.GetString("Password_New", resourceCulture);
            }
        }
        
        internal static string Confirmation_Logout {
            get {
                return ResourceManager.GetString("Confirmation_Logout", resourceCulture);
            }
        }
        
        internal static string Profile_BodyGoal {
            get {
                return ResourceManager.GetString("Profile_BodyGoal", resourceCulture);
            }
        }
        
        internal static string Goal_TargetWeight {
            get {
                return ResourceManager.GetString("Goal_TargetWeight", resourceCulture);
            }
        }
        
        internal static string Goal_Type {
            get {
                return ResourceManager.GetString("Goal_Type", resourceCulture);
            }
        }
        
        internal static string Goal_SelectType {
            get {
                return ResourceManager.GetString("Goal_SelectType", resourceCulture);
            }
        }
        
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        internal static string WorkoutType_StrengthTraining {
            get {
                return ResourceManager.GetString("WorkoutType_StrengthTraining", resourceCulture);
            }
        }
        
        internal static string WorkoutType_StrengthCardio {
            get {
                return ResourceManager.GetString("WorkoutType_StrengthCardio", resourceCulture);
            }
        }
        
        internal static string WorkoutType_Hypertrophy {
            get {
                return ResourceManager.GetString("WorkoutType_Hypertrophy", resourceCulture);
            }
        }
        
        internal static string GoalType_FatLoss {
            get {
                return ResourceManager.GetString("GoalType_FatLoss", resourceCulture);
            }
        }
        
        internal static string GoalType_WeightGain {
            get {
                return ResourceManager.GetString("GoalType_WeightGain", resourceCulture);
            }
        }
        
        internal static string GoalType_MuscleGain {
            get {
                return ResourceManager.GetString("GoalType_MuscleGain", resourceCulture);
            }
        }
        
        internal static string Profile_EditProfile {
            get {
                return ResourceManager.GetString("Profile_EditProfile", resourceCulture);
            }
        }
        
        internal static string Profile_Username {
            get {
                return ResourceManager.GetString("Profile_Username", resourceCulture);
            }
        }
        
        internal static string Profile_BirthDate {
            get {
                return ResourceManager.GetString("Profile_BirthDate", resourceCulture);
            }
        }
        
        internal static string Profile_Gender {
            get {
                return ResourceManager.GetString("Profile_Gender", resourceCulture);
            }
        }
        
        internal static string Confirm_UpdatePlan_Title {
            get {
                return ResourceManager.GetString("Confirm_UpdatePlan_Title", resourceCulture);
            }
        }
        
        internal static string Confirm_UpdatePlan_Message {
            get {
                return ResourceManager.GetString("Confirm_UpdatePlan_Message", resourceCulture);
            }
        }
        
        internal static string Success_ProfileUpdated {
            get {
                return ResourceManager.GetString("Success_ProfileUpdated", resourceCulture);
            }
        }
        
        internal static string Success_GoalUpdated {
            get {
                return ResourceManager.GetString("Success_GoalUpdated", resourceCulture);
            }
        }
        
        internal static string Success_NutritionUpdated {
            get {
                return ResourceManager.GetString("Success_NutritionUpdated", resourceCulture);
            }
        }
        
        internal static string Success_WorkoutUpdated {
            get {
                return ResourceManager.GetString("Success_WorkoutUpdated", resourceCulture);
            }
        }
        
        internal static string Success_PlanUpdated {
            get {
                return ResourceManager.GetString("Success_PlanUpdated", resourceCulture);
            }
        }
        
        internal static string Success_PasswordChanged {
            get {
                return ResourceManager.GetString("Success_PasswordChanged", resourceCulture);
            }
        }
        
        internal static string Error_InvalidInput {
            get {
                return ResourceManager.GetString("Error_InvalidInput", resourceCulture);
            }
        }
        
        internal static string Confirm_Logout_Title {
            get {
                return ResourceManager.GetString("Confirm_Logout_Title", resourceCulture);
            }
        }
        
        internal static string Confirm_Logout_Message {
            get {
                return ResourceManager.GetString("Confirm_Logout_Message", resourceCulture);
            }
        }
        
        internal static string Goal_Title {
            get {
                return ResourceManager.GetString("Goal_Title", resourceCulture);
            }
        }
        
        internal static string Goal_TitlePlaceholder {
            get {
                return ResourceManager.GetString("Goal_TitlePlaceholder", resourceCulture);
            }
        }
        
        internal static string Goal_Description {
            get {
                return ResourceManager.GetString("Goal_Description", resourceCulture);
            }
        }
        
        internal static string Goal_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("Goal_DescriptionPlaceholder", resourceCulture);
            }
        }
        
        internal static string Goal_DueDate {
            get {
                return ResourceManager.GetString("Goal_DueDate", resourceCulture);
            }
        }
        
        internal static string Error_UsernameTooLong {
            get {
                return ResourceManager.GetString("Error_UsernameTooLong", resourceCulture);
            }
        }
        
        internal static string Error_InvalidAge {
            get {
                return ResourceManager.GetString("Error_InvalidAge", resourceCulture);
            }
        }
        
        internal static string Error_InvalidWeightRange {
            get {
                return ResourceManager.GetString("Error_InvalidWeightRange", resourceCulture);
            }
        }
        
        internal static string Error_InvalidHeightRange {
            get {
                return ResourceManager.GetString("Error_InvalidHeightRange", resourceCulture);
            }
        }
        
        internal static string Error_TitleRequired {
            get {
                return ResourceManager.GetString("Error_TitleRequired", resourceCulture);
            }
        }
        
        internal static string Error_TitleTooLong {
            get {
                return ResourceManager.GetString("Error_TitleTooLong", resourceCulture);
            }
        }
        
        internal static string Error_DescriptionTooLong {
            get {
                return ResourceManager.GetString("Error_DescriptionTooLong", resourceCulture);
            }
        }
        
        internal static string Error_DateMustBeFuture {
            get {
                return ResourceManager.GetString("Error_DateMustBeFuture", resourceCulture);
            }
        }
        
        internal static string Error_CaloriesRange {
            get {
                return ResourceManager.GetString("Error_CaloriesRange", resourceCulture);
            }
        }
        
        internal static string Error_MacrosPositive {
            get {
                return ResourceManager.GetString("Error_MacrosPositive", resourceCulture);
            }
        }
        
        internal static string Error_WaterRange {
            get {
                return ResourceManager.GetString("Error_WaterRange", resourceCulture);
            }
        }
        
        internal static string Error_WorkoutFrequency {
            get {
                return ResourceManager.GetString("Error_WorkoutFrequency", resourceCulture);
            }
        }
        
        internal static string Error_WorkoutDuration {
            get {
                return ResourceManager.GetString("Error_WorkoutDuration", resourceCulture);
            }
        }
        
        internal static string Error_CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("Error_CurrentPasswordRequired", resourceCulture);
            }
        }
        
        internal static string Error_PasswordTooShort {
            get {
                return ResourceManager.GetString("Error_PasswordTooShort", resourceCulture);
            }
        }
        
        internal static string Error_NewPasswordSame {
            get {
                return ResourceManager.GetString("Error_NewPasswordSame", resourceCulture);
            }
        }
        
        internal static string Action_Confirm {
            get {
                return ResourceManager.GetString("Action_Confirm", resourceCulture);
            }
        }
        
        internal static string Error_DeadlineTooClose {
            get {
                return ResourceManager.GetString("Error_DeadlineTooClose", resourceCulture);
            }
        }
        
        internal static string Error_FatLossUnsafe {
            get {
                return ResourceManager.GetString("Error_FatLossUnsafe", resourceCulture);
            }
        }
        
        internal static string Error_MuscleGainUnrealistic {
            get {
                return ResourceManager.GetString("Error_MuscleGainUnrealistic", resourceCulture);
            }
        }
        
        internal static string Error_TargetWeightRealistic {
            get {
                return ResourceManager.GetString("Error_TargetWeightRealistic", resourceCulture);
            }
        }
        
        internal static string Action_Finish {
            get {
                return ResourceManager.GetString("Action_Finish", resourceCulture);
            }
        }
        
        internal static string Action_Next {
            get {
                return ResourceManager.GetString("Action_Next", resourceCulture);
            }
        }
        
        internal static string Action_Back {
            get {
                return ResourceManager.GetString("Action_Back", resourceCulture);
            }
        }
        
        internal static string Placeholder_ConfirmPassword {
            get {
                return ResourceManager.GetString("Placeholder_ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string Reg_Title_Credentials {
            get {
                return ResourceManager.GetString("Reg_Title_Credentials", resourceCulture);
            }
        }
        
        internal static string Reg_Title_Personal {
            get {
                return ResourceManager.GetString("Reg_Title_Personal", resourceCulture);
            }
        }
        
        internal static string Reg_Title_Measurements {
            get {
                return ResourceManager.GetString("Reg_Title_Measurements", resourceCulture);
            }
        }
        
        internal static string Reg_Title_Goal {
            get {
                return ResourceManager.GetString("Reg_Title_Goal", resourceCulture);
            }
        }
        
        internal static string Reg_GoalDisclaimer {
            get {
                return ResourceManager.GetString("Reg_GoalDisclaimer", resourceCulture);
            }
        }
        
        internal static string Reg_WelcomeTitle {
            get {
                return ResourceManager.GetString("Reg_WelcomeTitle", resourceCulture);
            }
        }
        
        internal static string Reg_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Reg_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string Reg_EmailTaken {
            get {
                return ResourceManager.GetString("Reg_EmailTaken", resourceCulture);
            }
        }
        
        internal static string Reg_ConfirmPasswordError {
            get {
                return ResourceManager.GetString("Reg_ConfirmPasswordError", resourceCulture);
            }
        }
        
        internal static string Reg_Subtitle_Personal {
            get {
                return ResourceManager.GetString("Reg_Subtitle_Personal", resourceCulture);
            }
        }
        
        internal static string Reg_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Reg_UsernamePlaceholder", resourceCulture);
            }
        }
        
        internal static string BMI_Title {
            get {
                return ResourceManager.GetString("BMI_Title", resourceCulture);
            }
        }
        
        internal static string BMI_Underweight {
            get {
                return ResourceManager.GetString("BMI_Underweight", resourceCulture);
            }
        }
        
        internal static string BMI_Normal {
            get {
                return ResourceManager.GetString("BMI_Normal", resourceCulture);
            }
        }
        
        internal static string BMI_Overweight {
            get {
                return ResourceManager.GetString("BMI_Overweight", resourceCulture);
            }
        }
        
        internal static string BMI_Obesity {
            get {
                return ResourceManager.GetString("BMI_Obesity", resourceCulture);
            }
        }
        
        internal static string BMI_Desc_Underweight {
            get {
                return ResourceManager.GetString("BMI_Desc_Underweight", resourceCulture);
            }
        }
        
        internal static string BMI_Desc_Normal {
            get {
                return ResourceManager.GetString("BMI_Desc_Normal", resourceCulture);
            }
        }
        
        internal static string BMI_Desc_Overweight {
            get {
                return ResourceManager.GetString("BMI_Desc_Overweight", resourceCulture);
            }
        }
        
        internal static string BMI_Desc_Obesity {
            get {
                return ResourceManager.GetString("BMI_Desc_Obesity", resourceCulture);
            }
        }
        
        internal static string Reg_Subtitle_Measurements {
            get {
                return ResourceManager.GetString("Reg_Subtitle_Measurements", resourceCulture);
            }
        }
        
        internal static string Reg_Height {
            get {
                return ResourceManager.GetString("Reg_Height", resourceCulture);
            }
        }
        
        internal static string Reg_Weight {
            get {
                return ResourceManager.GetString("Reg_Weight", resourceCulture);
            }
        }
        
        internal static string Error_TargetMustBeLower {
            get {
                return ResourceManager.GetString("Error_TargetMustBeLower", resourceCulture);
            }
        }
        
        internal static string Error_TargetMustBeHigher {
            get {
                return ResourceManager.GetString("Error_TargetMustBeHigher", resourceCulture);
            }
        }
        
        internal static string Error_TargetWeightTooLow {
            get {
                return ResourceManager.GetString("Error_TargetWeightTooLow", resourceCulture);
            }
        }
        
        internal static string Error_TargetWeightTooHigh {
            get {
                return ResourceManager.GetString("Error_TargetWeightTooHigh", resourceCulture);
            }
        }
        
        internal static string Error_WeightGainUnrealistic {
            get {
                return ResourceManager.GetString("Error_WeightGainUnrealistic", resourceCulture);
            }
        }
        
        internal static string Reg_InitialBodyGoalTitle {
            get {
                return ResourceManager.GetString("Reg_InitialBodyGoalTitle", resourceCulture);
            }
        }
        
        internal static string Reg_InitialBodyGoalDesc {
            get {
                return ResourceManager.GetString("Reg_InitialBodyGoalDesc", resourceCulture);
            }
        }
        
        internal static string Goal_DaysLeft {
            get {
                return ResourceManager.GetString("Goal_DaysLeft", resourceCulture);
            }
        }
        
        internal static string Goal_NoDeadline {
            get {
                return ResourceManager.GetString("Goal_NoDeadline", resourceCulture);
            }
        }
        
        internal static string Reg_Commitment_Title_Male {
            get {
                return ResourceManager.GetString("Reg_Commitment_Title_Male", resourceCulture);
            }
        }
        
        internal static string Reg_Commitment_Subtitle_Male {
            get {
                return ResourceManager.GetString("Reg_Commitment_Subtitle_Male", resourceCulture);
            }
        }
        
        internal static string Reg_Commitment_Title_Female {
            get {
                return ResourceManager.GetString("Reg_Commitment_Title_Female", resourceCulture);
            }
        }
        
        internal static string Reg_Commitment_Subtitle_Female {
            get {
                return ResourceManager.GetString("Reg_Commitment_Subtitle_Female", resourceCulture);
            }
        }
        
        internal static string Reg_Commitment_Commit {
            get {
                return ResourceManager.GetString("Reg_Commitment_Commit", resourceCulture);
            }
        }
        
        internal static string Hint_SwipeBack {
            get {
                return ResourceManager.GetString("Hint_SwipeBack", resourceCulture);
            }
        }
        
        internal static string Workout_Stats_Title {
            get {
                return ResourceManager.GetString("Workout_Stats_Title", resourceCulture);
            }
        }
        
        internal static string Workout_MyPrograms_Title {
            get {
                return ResourceManager.GetString("Workout_MyPrograms_Title", resourceCulture);
            }
        }
        
        internal static string Action_StartWorkout {
            get {
                return ResourceManager.GetString("Action_StartWorkout", resourceCulture);
            }
        }
        
        internal static string Workout_Done {
            get {
                return ResourceManager.GetString("Workout_Done", resourceCulture);
            }
        }
        
        internal static string Workout_EmptyPrograms {
            get {
                return ResourceManager.GetString("Workout_EmptyPrograms", resourceCulture);
            }
        }
        
        internal static string Workout_CreateProgram {
            get {
                return ResourceManager.GetString("Workout_CreateProgram", resourceCulture);
            }
        }
        
        internal static string Workout_More {
            get {
                return ResourceManager.GetString("Workout_More", resourceCulture);
            }
        }
        
        internal static string Workout_Sets {
            get {
                return ResourceManager.GetString("Workout_Sets", resourceCulture);
            }
        }
        
        internal static string Workout_Rest {
            get {
                return ResourceManager.GetString("Workout_Rest", resourceCulture);
            }
        }
        
        internal static string Workout_Kg {
            get {
                return ResourceManager.GetString("Workout_Kg", resourceCulture);
            }
        }
        
        internal static string Workout_Reps {
            get {
                return ResourceManager.GetString("Workout_Reps", resourceCulture);
            }
        }
        
        internal static string Action_AddSet {
            get {
                return ResourceManager.GetString("Action_AddSet", resourceCulture);
            }
        }
        
        internal static string Action_FinishWorkout {
            get {
                return ResourceManager.GetString("Action_FinishWorkout", resourceCulture);
            }
        }
        
        internal static string Title_DeleteExercise {
            get {
                return ResourceManager.GetString("Title_DeleteExercise", resourceCulture);
            }
        }
        
        internal static string Msg_DeleteExerciseConfirm {
            get {
                return ResourceManager.GetString("Msg_DeleteExerciseConfirm", resourceCulture);
            }
        }
        
        internal static string Title_FinishWorkout {
            get {
                return ResourceManager.GetString("Title_FinishWorkout", resourceCulture);
            }
        }
        
        internal static string Msg_FinishWorkoutConfirm {
            get {
                return ResourceManager.GetString("Msg_FinishWorkoutConfirm", resourceCulture);
            }
        }
        
        internal static string Title_CancelWorkout {
            get {
                return ResourceManager.GetString("Title_CancelWorkout", resourceCulture);
            }
        }
        
        internal static string Msg_CancelWorkoutConfirm {
            get {
                return ResourceManager.GetString("Msg_CancelWorkoutConfirm", resourceCulture);
            }
        }
        
        internal static string Error_MaxSetsReached {
            get {
                return ResourceManager.GetString("Error_MaxSetsReached", resourceCulture);
            }
        }
        
        internal static string Error_CannotDeleteLastSet {
            get {
                return ResourceManager.GetString("Error_CannotDeleteLastSet", resourceCulture);
            }
        }
        
        internal static string Error_NoExercisesInWorkout {
            get {
                return ResourceManager.GetString("Error_NoExercisesInWorkout", resourceCulture);
            }
        }
        
        internal static string Error_ExerciseWithoutSets {
            get {
                return ResourceManager.GetString("Error_ExerciseWithoutSets", resourceCulture);
            }
        }
        
        internal static string Title_AdjustDuration {
            get {
                return ResourceManager.GetString("Title_AdjustDuration", resourceCulture);
            }
        }
        
        internal static string Placeholder_EnterDurationMinutes {
            get {
                return ResourceManager.GetString("Placeholder_EnterDurationMinutes", resourceCulture);
            }
        }
        
        internal static string Error_DurationTooShort {
            get {
                return ResourceManager.GetString("Error_DurationTooShort", resourceCulture);
            }
        }
        
        internal static string Error_DurationTooLong {
            get {
                return ResourceManager.GetString("Error_DurationTooLong", resourceCulture);
            }
        }
        
        internal static string Error_InvalidNumber {
            get {
                return ResourceManager.GetString("Error_InvalidNumber", resourceCulture);
            }
        }
        
        internal static string Search_AllExercises {
            get {
                return ResourceManager.GetString("Search_AllExercises", resourceCulture);
            }
        }
        
        internal static string Search_Placeholder_Exercise {
            get {
                return ResourceManager.GetString("Search_Placeholder_Exercise", resourceCulture);
            }
        }
        
        internal static string Search_Filter {
            get {
                return ResourceManager.GetString("Search_Filter", resourceCulture);
            }
        }
        
        internal static string Filter_Muscles {
            get {
                return ResourceManager.GetString("Filter_Muscles", resourceCulture);
            }
        }
        
        internal static string Filter_BodyParts {
            get {
                return ResourceManager.GetString("Filter_BodyParts", resourceCulture);
            }
        }
        
        internal static string Filter_Equipment {
            get {
                return ResourceManager.GetString("Filter_Equipment", resourceCulture);
            }
        }
        
        internal static string Exercise_Instructions {
            get {
                return ResourceManager.GetString("Exercise_Instructions", resourceCulture);
            }
        }
        
        internal static string Action_AddExercise {
            get {
                return ResourceManager.GetString("Action_AddExercise", resourceCulture);
            }
        }
        
        internal static string Title_NewProgram {
            get {
                return ResourceManager.GetString("Title_NewProgram", resourceCulture);
            }
        }
        
        internal static string Placeholder_EnterProgramName {
            get {
                return ResourceManager.GetString("Placeholder_EnterProgramName", resourceCulture);
            }
        }
        
        internal static string Title_RenameProgram {
            get {
                return ResourceManager.GetString("Title_RenameProgram", resourceCulture);
            }
        }
        
        internal static string Msg_EnterNewName {
            get {
                return ResourceManager.GetString("Msg_EnterNewName", resourceCulture);
            }
        }
        
        internal static string Placeholder_EnterDescription {
            get {
                return ResourceManager.GetString("Placeholder_EnterDescription", resourceCulture);
            }
        }
        
        internal static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        internal static string Title_UnsavedChanges {
            get {
                return ResourceManager.GetString("Title_UnsavedChanges", resourceCulture);
            }
        }
        
        internal static string Msg_UnsavedChangesConfirm {
            get {
                return ResourceManager.GetString("Msg_UnsavedChangesConfirm", resourceCulture);
            }
        }
        
        internal static string Error_ProgramNameTooLong {
            get {
                return ResourceManager.GetString("Error_ProgramNameTooLong", resourceCulture);
            }
        }
        
        internal static string Error_ProgramDescriptionTooLong {
            get {
                return ResourceManager.GetString("Error_ProgramDescriptionTooLong", resourceCulture);
            }
        }
        
        internal static string Error_TooManyExercises {
            get {
                return ResourceManager.GetString("Error_TooManyExercises", resourceCulture);
            }
        }
        
        internal static string Workout_Description {
            get {
                return ResourceManager.GetString("Workout_Description", resourceCulture);
            }
        }
        
        internal static string Workout_Exercises {
            get {
                return ResourceManager.GetString("Workout_Exercises", resourceCulture);
            }
        }
        
        internal static string Title_DeleteProgram {
            get {
                return ResourceManager.GetString("Title_DeleteProgram", resourceCulture);
            }
        }
        
        internal static string Msg_DeleteProgramConfirm {
            get {
                return ResourceManager.GetString("Msg_DeleteProgramConfirm", resourceCulture);
            }
        }
        
        internal static string Tab_Search {
            get {
                return ResourceManager.GetString("Tab_Search", resourceCulture);
            }
        }
        
        internal static string Tab_MyFood {
            get {
                return ResourceManager.GetString("Tab_MyFood", resourceCulture);
            }
        }
        
        internal static string Tab_Recipes {
            get {
                return ResourceManager.GetString("Tab_Recipes", resourceCulture);
            }
        }
        
        internal static string Action_CreateProduct {
            get {
                return ResourceManager.GetString("Action_CreateProduct", resourceCulture);
            }
        }
        
        internal static string Action_CreateRecipe {
            get {
                return ResourceManager.GetString("Action_CreateRecipe", resourceCulture);
            }
        }
        
        internal static string MyFood_EmptyList {
            get {
                return ResourceManager.GetString("MyFood_EmptyList", resourceCulture);
            }
        }
        
        internal static string CustomFood_Name {
            get {
                return ResourceManager.GetString("CustomFood_Name", resourceCulture);
            }
        }
        
        internal static string CustomFood_Brand {
            get {
                return ResourceManager.GetString("CustomFood_Brand", resourceCulture);
            }
        }
        
        internal static string CustomFood_Barcode {
            get {
                return ResourceManager.GetString("CustomFood_Barcode", resourceCulture);
            }
        }
        
        internal static string CustomFood_Macros {
            get {
                return ResourceManager.GetString("CustomFood_Macros", resourceCulture);
            }
        }
        
        internal static string CustomFood_Serving {
            get {
                return ResourceManager.GetString("CustomFood_Serving", resourceCulture);
            }
        }
        
        internal static string CustomFood_ServingSize {
            get {
                return ResourceManager.GetString("CustomFood_ServingSize", resourceCulture);
            }
        }
        
        internal static string CustomFood_AdditionalInfo {
            get {
                return ResourceManager.GetString("CustomFood_AdditionalInfo", resourceCulture);
            }
        }
        
        internal static string CustomFood_ServingUnit {
            get {
                return ResourceManager.GetString("CustomFood_ServingUnit", resourceCulture);
            }
        }
        
        internal static string Error_FoodNameRequired {
            get {
                return ResourceManager.GetString("Error_FoodNameRequired", resourceCulture);
            }
        }
        
        internal static string Error_FoodNameTooLong {
            get {
                return ResourceManager.GetString("Error_FoodNameTooLong", resourceCulture);
            }
        }
        
        internal static string Error_InvalidServingSize {
            get {
                return ResourceManager.GetString("Error_InvalidServingSize", resourceCulture);
            }
        }
        
        internal static string Success_CustomFoodCreated {
            get {
                return ResourceManager.GetString("Success_CustomFoodCreated", resourceCulture);
            }
        }
        
        internal static string Success_CustomFoodUpdated {
            get {
                return ResourceManager.GetString("Success_CustomFoodUpdated", resourceCulture);
            }
        }
        
        internal static string Title_DeleteFood {
            get {
                return ResourceManager.GetString("Title_DeleteFood", resourceCulture);
            }
        }
        
        internal static string Message_ConfirmDeleteFood {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteFood", resourceCulture);
            }
        }
        
        internal static string Recipe_Name {
            get {
                return ResourceManager.GetString("Recipe_Name", resourceCulture);
            }
        }
        
        internal static string Recipe_NamePlaceholder {
            get {
                return ResourceManager.GetString("Recipe_NamePlaceholder", resourceCulture);
            }
        }
        
        internal static string Recipe_Description {
            get {
                return ResourceManager.GetString("Recipe_Description", resourceCulture);
            }
        }
        
        internal static string Recipe_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("Recipe_DescriptionPlaceholder", resourceCulture);
            }
        }
        
        internal static string Recipe_Ingredients {
            get {
                return ResourceManager.GetString("Recipe_Ingredients", resourceCulture);
            }
        }
        
        internal static string Recipe_TotalMacros {
            get {
                return ResourceManager.GetString("Recipe_TotalMacros", resourceCulture);
            }
        }
        
        internal static string Recipe_EmptyList {
            get {
                return ResourceManager.GetString("Recipe_EmptyList", resourceCulture);
            }
        }
        
        internal static string Recipe_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Recipe_SearchPlaceholder", resourceCulture);
            }
        }
        
        internal static string Recipe_NoResults {
            get {
                return ResourceManager.GetString("Recipe_NoResults", resourceCulture);
            }
        }
        
        internal static string Recipe_MoreIngredients {
            get {
                return ResourceManager.GetString("Recipe_MoreIngredients", resourceCulture);
            }
        }
        
        internal static string Action_SaveAsRecipe {
            get {
                return ResourceManager.GetString("Action_SaveAsRecipe", resourceCulture);
            }
        }
        
        internal static string Title_DeleteRecipe {
            get {
                return ResourceManager.GetString("Title_DeleteRecipe", resourceCulture);
            }
        }
        
        internal static string Message_ConfirmDeleteRecipe {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteRecipe", resourceCulture);
            }
        }
        
        internal static string Title_EditRecipe {
            get {
                return ResourceManager.GetString("Title_EditRecipe", resourceCulture);
            }
        }
        
        internal static string Error_RecipeNameRequired {
            get {
                return ResourceManager.GetString("Error_RecipeNameRequired", resourceCulture);
            }
        }
        
        internal static string Error_RecipeNameTooLong {
            get {
                return ResourceManager.GetString("Error_RecipeNameTooLong", resourceCulture);
            }
        }
        
        internal static string Error_RecipeNoIngredients {
            get {
                return ResourceManager.GetString("Error_RecipeNoIngredients", resourceCulture);
            }
        }
        
        internal static string Success_RecipeCreated {
            get {
                return ResourceManager.GetString("Success_RecipeCreated", resourceCulture);
            }
        }
        
        internal static string Success_RecipeUpdated {
            get {
                return ResourceManager.GetString("Success_RecipeUpdated", resourceCulture);
            }
        }
    }
}
