// <auto-generated />
using System;
using ForgeFit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeFit.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203122355_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.FoodAggregate.DrinkEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DrinkEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_DrinkEntries_VolumeMlCheck", "VolumeMl > 0");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.FoodAggregate.FoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayTime")
                        .HasColumnType("int");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_FoodEntries_CaloriesCheck", "Calories > 0");

                            t.HasCheckConstraint("CK_FoodEntries_CarbsCheck", "Carbs > 0");

                            t.HasCheckConstraint("CK_FoodEntries_DayTimeCheck", "DayTime IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_FoodEntries_FatCheck", "Fat > 0");

                            t.HasCheckConstraint("CK_FoodEntries_ProteinCheck", "Protein > 0");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.GoalAggregate.BodyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalStatus")
                        .HasColumnType("int");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyGoals", null, t =>
                        {
                            t.HasCheckConstraint("CK_BodyGoals_GoalStatusCheck", "GoalStatus IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_BodyGoals_GoalTypeCheck", "GoalType IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_BodyGoals_WeightGoal_UnitCheck", "WeightGoal_Unit IN (1, 2)");

                            t.HasCheckConstraint("CK_BodyGoals_WeightGoal_ValueCheck", "WeightGoal_Value > 0");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.GoalAggregate.NutritionGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionGoals", null, t =>
                        {
                            t.HasCheckConstraint("CK_NutritionGoals_DailyNutritionPlan_CaloriesCheck", "DailyNutritionPlan_TargetCalories > 1000");

                            t.HasCheckConstraint("CK_NutritionGoals_DailyNutritionPlan_CarbsCheck", "DailyNutritionPlan_Carbs > 0");

                            t.HasCheckConstraint("CK_NutritionGoals_DailyNutritionPlan_FatCheck", "DailyNutritionPlan_Fat > 0");

                            t.HasCheckConstraint("CK_NutritionGoals_DailyNutritionPlan_ProteinCheck", "DailyNutritionPlan_Protein > 0");

                            t.HasCheckConstraint("CK_NutritionGoals_DailyNutritionPlan_WaterGoalMlCheck", "DailyNutritionPlan_WaterMl > 1000");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.GoalAggregate.WorkoutGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutGoals", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutGoals_WorkoutPlan_DurationCheck", "WorkoutPlan_Duration BETWEEN '00:10:00' AND '05:00:00'");

                            t.HasCheckConstraint("CK_WorkoutGoals_WorkoutPlan_WorkoutTypeCheck", "WorkoutPlan_WorkoutType IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_WorkoutGoals_WorkoutPlan_WorkoutsPerWeekCheck", "WorkoutPlan_WorkoutsPerWeek > 0 AND WorkoutPlan_WorkoutsPerWeek < 8");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.NotificationAggregate.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ScheduledAt")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Frequency_FrequencyUnitCheck", "Frequency_FrequencyUnit IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Notifications_Frequency_IntervalCheck", "Frequency_Interval > 0");

                            t.HasCheckConstraint("CK_Notifications_NotificationTypeCheck", "NotificationType IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.UserAggregate.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_HeightCheck", "HeightValue > 0");

                            t.HasCheckConstraint("CK_Users_HeightUnitCheck", "HeightUnit IN (1, 2)");

                            t.HasCheckConstraint("CK_Users_UserProfile_GenderCheck", "UserProfile_Gender IN (1, 2)");

                            t.HasCheckConstraint("CK_Users_WeightCheck", "WeightValue > 0");

                            t.HasCheckConstraint("CK_Users_WeightUnitCheck", "WeightUnit IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("WorkoutEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutEntries_WorkoutSchedule_DurationCheck", "WorkoutSchedule_Duration BETWEEN '00:10:00' AND '05:00:00'");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutExercisePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("WorkoutExercisePlans", (string)null);
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPrograms", (string)null);
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RestTime")
                        .HasColumnType("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutExercisePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutExercisePlanId");

                    b.ToTable("WorkoutSets", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSet_OrderCheck", "[Order] > 0");

                            t.HasCheckConstraint("CK_WorkoutSet_RepsCheck", "Reps > 0");

                            t.HasCheckConstraint("CK_WorkoutSets_WeightCheck", "WeightValue > 0");

                            t.HasCheckConstraint("CK_WorkoutSets_WeightUnitCheck", "WeightUnit IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.FoodAggregate.DrinkEntry", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.FoodAggregate.FoodEntry", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ForgeFit.Domain.ValueObjects.FoodValueObjects.FoodItem", "FoodItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(100.0);

                            b1.Property<double>("Calories")
                                .HasColumnType("float");

                            b1.Property<double>("Carbs")
                                .HasColumnType("float");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double>("Fat")
                                .HasColumnType("float");

                            b1.Property<Guid>("FoodEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double>("Protein")
                                .HasColumnType("float");

                            b1.Property<string>("ServingUnit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("g");

                            b1.HasKey("Id");

                            b1.HasIndex("FoodEntryId");

                            b1.ToTable("FoodItems", null, t =>
                                {
                                    t.HasCheckConstraint("CK_FoodItems_AmountCheck", "Amount > 0");

                                    t.HasCheckConstraint("CK_FoodItems_CaloriesCheck", "Calories > 0");

                                    t.HasCheckConstraint("CK_FoodItems_CarbsCheck", "Carbs > 0");

                                    t.HasCheckConstraint("CK_FoodItems_FatCheck", "Fat > 0");

                                    t.HasCheckConstraint("CK_FoodItems_ProteinCheck", "Protein > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("FoodEntryId");
                        });

                    b.Navigation("FoodItems");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.GoalAggregate.BodyGoal", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.Weight", "WeightGoal", b1 =>
                        {
                            b1.Property<Guid>("BodyGoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Unit")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("BodyGoalId");

                            b1.ToTable("BodyGoals");

                            b1.WithOwner()
                                .HasForeignKey("BodyGoalId");
                        });

                    b.Navigation("User");

                    b.Navigation("WeightGoal")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.GoalAggregate.NutritionGoal", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.GoalValueObjects.DailyNutritionPlan", "DailyNutritionPlan", b1 =>
                        {
                            b1.Property<Guid>("NutritionGoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Carbs")
                                .HasColumnType("int");

                            b1.Property<int>("Fat")
                                .HasColumnType("int");

                            b1.Property<int>("Protein")
                                .HasColumnType("int");

                            b1.Property<int>("TargetCalories")
                                .HasColumnType("int");

                            b1.Property<int>("WaterMl")
                                .HasColumnType("int");

                            b1.HasKey("NutritionGoalId");

                            b1.ToTable("NutritionGoals");

                            b1.WithOwner()
                                .HasForeignKey("NutritionGoalId");
                        });

                    b.Navigation("DailyNutritionPlan")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.GoalAggregate.WorkoutGoal", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.GoalValueObjects.WorkoutPlan", "WorkoutPlan", b1 =>
                        {
                            b1.Property<Guid>("WorkoutGoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("time");

                            b1.Property<int>("WorkoutType")
                                .HasColumnType("int");

                            b1.Property<int>("WorkoutsPerWeek")
                                .HasColumnType("int");

                            b1.HasKey("WorkoutGoalId");

                            b1.ToTable("WorkoutGoals");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutGoalId");
                        });

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.NotificationAggregate.Notification", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.Frequency", "Frequency", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FrequencyUnit")
                                .HasColumnType("int");

                            b1.Property<int>("Interval")
                                .HasColumnType("int");

                            b1.HasKey("NotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.UserAggregate.RefreshToken", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("ForgeFit.Domain.ValueObjects.UserValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.UserValueObjects.UserProfile", "UserProfile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AvatarUrl")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("ForgeFit.Domain.ValueObjects.UserValueObjects.DateOfBirth", "DateOfBirth", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("Value")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("UserProfileUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId");
                                });

                            b1.OwnsOne("ForgeFit.Domain.ValueObjects.UserValueObjects.Height", "Height", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Unit")
                                        .HasColumnType("int")
                                        .HasColumnName("HeightUnit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("HeightValue");

                                    b2.HasKey("UserProfileUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId");
                                });

                            b1.OwnsOne("ForgeFit.Domain.ValueObjects.Weight", "Weight", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Unit")
                                        .HasColumnType("int")
                                        .HasColumnName("WeightUnit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("WeightValue");

                                    b2.HasKey("UserProfileUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId");
                                });

                            b1.Navigation("DateOfBirth")
                                .IsRequired();

                            b1.Navigation("Height")
                                .IsRequired();

                            b1.Navigation("Weight")
                                .IsRequired();
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutEntry", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutEntries")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.Schedule", "WorkoutSchedule", b1 =>
                        {
                            b1.Property<Guid>("WorkoutEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time");

                            b1.HasKey("WorkoutEntryId");

                            b1.ToTable("WorkoutEntries");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutEntryId");
                        });

                    b.OwnsMany("ForgeFit.Domain.ValueObjects.WorkoutValueObjects.PerformedExercise", "PerformedExercises", b1 =>
                        {
                            b1.Property<Guid>("WorkoutEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.HasKey("WorkoutEntryId", "Id");

                            b1.ToTable("PerformedExercises", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutEntryId");

                            b1.OwnsOne("ForgeFit.Domain.ValueObjects.WorkoutValueObjects.WorkoutExercise", "Snapshot", b2 =>
                                {
                                    b2.Property<Guid>("PerformedExerciseWorkoutEntryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("PerformedExerciseId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BodyParts")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Equipment")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ExternalId")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<string>("GifUrl")
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)");

                                    b2.Property<string>("Instructions")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("SecondaryMuscles")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("TargetMuscles")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PerformedExerciseWorkoutEntryId", "PerformedExerciseId");

                                    b2.ToTable("PerformedExercises");

                                    b2.WithOwner()
                                        .HasForeignKey("PerformedExerciseWorkoutEntryId", "PerformedExerciseId");
                                });

                            b1.OwnsMany("ForgeFit.Domain.ValueObjects.WorkoutValueObjects.PerformedSet", "Sets", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutEntryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("PerformedExerciseId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<bool>("IsCompleted")
                                        .HasColumnType("bit");

                                    b2.Property<int>("Order")
                                        .HasColumnType("int");

                                    b2.Property<int>("Reps")
                                        .HasColumnType("int");

                                    b2.HasKey("WorkoutEntryId", "PerformedExerciseId", "Id");

                                    b2.ToTable("PerformedSets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutEntryId", "PerformedExerciseId");

                                    b2.OwnsOne("ForgeFit.Domain.ValueObjects.Weight", "Weight", b3 =>
                                        {
                                            b3.Property<Guid>("PerformedSetWorkoutEntryId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("PerformedSetPerformedExerciseId")
                                                .HasColumnType("int");

                                            b3.Property<int>("PerformedSetId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Unit")
                                                .HasColumnType("int")
                                                .HasColumnName("WeightUnit");

                                            b3.Property<double>("Value")
                                                .HasColumnType("float")
                                                .HasColumnName("WeightValue");

                                            b3.HasKey("PerformedSetWorkoutEntryId", "PerformedSetPerformedExerciseId", "PerformedSetId");

                                            b3.ToTable("PerformedSets");

                                            b3.WithOwner()
                                                .HasForeignKey("PerformedSetWorkoutEntryId", "PerformedSetPerformedExerciseId", "PerformedSetId");
                                        });

                                    b2.Navigation("Weight")
                                        .IsRequired();
                                });

                            b1.Navigation("Sets");

                            b1.Navigation("Snapshot")
                                .IsRequired();
                        });

                    b.Navigation("PerformedExercises");

                    b.Navigation("User");

                    b.Navigation("WorkoutProgram");

                    b.Navigation("WorkoutSchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutExercisePlan", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutExercisePlans")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.WorkoutValueObjects.WorkoutExercise", "WorkoutExercise", b1 =>
                        {
                            b1.Property<Guid>("WorkoutExercisePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BodyParts")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Equipment")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("GifUrl")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Instructions")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("SecondaryMuscles")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TargetMuscles")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WorkoutExercisePlanId");

                            b1.ToTable("WorkoutExercisePlans");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutExercisePlanId");
                        });

                    b.Navigation("WorkoutExercise")
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutProgram", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutSet", b =>
                {
                    b.HasOne("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutExercisePlan", "WorkoutExercisePlan")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutExercisePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForgeFit.Domain.ValueObjects.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("WorkoutSetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("WeightUnit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("WeightValue");

                            b1.HasKey("WorkoutSetId");

                            b1.ToTable("WorkoutSets");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutSetId");
                        });

                    b.Navigation("Weight")
                        .IsRequired();

                    b.Navigation("WorkoutExercisePlan");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutExercisePlan", b =>
                {
                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("ForgeFit.Domain.Aggregates.WorkoutAggregate.WorkoutProgram", b =>
                {
                    b.Navigation("WorkoutEntries");

                    b.Navigation("WorkoutExercisePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
